### Register

POST http://localhost:5000/api/User/Register HTTP/1.1
Content-Type: application/json

{
    "userName": "test",
    "password": "111111"
}

### Login

POST http://localhost:5000/api/User/Login HTTP/1.1
Content-Type: application/json

{
    "userName": "test",
    "password": "111111"
}


### GetUserInfo

GET http://localhost:5000/api/User/UserInfo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm4iOiJmYTRmNzcxNS04NGY3LTQyNDEtYjUxNC1lN2JiNTE3YjMwN2IiLCJzdWIiOiJ0ZXN0IiwianRpIjoiOTBkN2ZkNTAtYjYyNS00NTlmLThiNjYtMTFiNGE4MWM1YmM5IiwiaWF0IjoxNTI5NzYzNzkzLCJuYmYiOjE1Mjk3NjM3OTMsImV4cCI6MTUyOTc5Mzc5MywiaXNzIjoiU2ltcGxlVXNlcnMiLCJhdWQiOiJTaW1wbGVVc2Vyc0F1ZGllbmNlIn0.EMfOG9wmurxsMTCwrJTcjCXsRvDyRADN7BqIiaTv8VU


### Update UserInfo

POST http://localhost:5000/api/User/UserInfo HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm4iOiJmYTRmNzcxNS04NGY3LTQyNDEtYjUxNC1lN2JiNTE3YjMwN2IiLCJzdWIiOiJ0ZXN0IiwianRpIjoiOTBkN2ZkNTAtYjYyNS00NTlmLThiNjYtMTFiNGE4MWM1YmM5IiwiaWF0IjoxNTI5NzYzNzkzLCJuYmYiOjE1Mjk3NjM3OTMsImV4cCI6MTUyOTc5Mzc5MywiaXNzIjoiU2ltcGxlVXNlcnMiLCJhdWQiOiJTaW1wbGVVc2Vyc0F1ZGllbmNlIn0.EMfOG9wmurxsMTCwrJTcjCXsRvDyRADN7BqIiaTv8VU

{
    "name": "测试",
    "mobile": "13900000000",
    "email": "test1@test.com"
}

