### Register

POST http://localhost:5000/api/User/Register HTTP/1.1
Content-Type: application/json

{
    "userName": "test",
    "password": "111111"
}

### Login

POST http://localhost:5000/api/User/Login HTTP/1.1
Content-Type: application/json

{
    "userName": "test",
    "password": "111111"
}


### GetUserInfo

GET http://localhost:5000/api/User/UserInfo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm4iOiJlNzQyNmY1ZS0yY2NiLTQ4MDktODZjNy1iY2EzODE3ZjE1OTQiLCJzdWIiOiJ0ZXN0IiwianRpIjoiNzlhMzBhYjAtMzRkMS00ZDM0LTk0MzAtYzFiNjI5ZmMwMDI5IiwiaWF0IjoxNTI2MjEzODY1LCJuYmYiOjE1MjYyMTM4NjQsImV4cCI6MTUyNjI0Mzg2NCwiaXNzIjoiU2ltcGxlVXNlcnMiLCJhdWQiOiJTaW1wbGVVc2Vyc0F1ZGllbmNlIn0.YDtWlWnTA7xPFqWz4cQc4okzyiFM6hUdqmSH1psPKy4


### Update UserInfo

POST http://localhost:5000/api/User/UserInfo HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm4iOiJlNzQyNmY1ZS0yY2NiLTQ4MDktODZjNy1iY2EzODE3ZjE1OTQiLCJzdWIiOiJ0ZXN0IiwianRpIjoiMDNlY2MyZmEtMzk3Zi00MGNlLTkyZDYtYmUwMTBkZTNiODJlIiwiaWF0IjoxNTI2MTk4OTUwLCJuYmYiOjE1MjYxOTg5NTAsImV4cCI6MTUyNjIyODk1MCwiaXNzIjoiU2ltcGxlVXNlcnMiLCJhdWQiOiJTaW1wbGVVc2Vyc0F1ZGllbmNlIn0.JMLwPidWNHpHfOnFygz1SPoHzGekO7dekpXD--P9yag

{
    "name": "测试",
    "mobile": "13900000000",
    "email": "test1@test.com"
}

